# Generated by Django 3.1.7 on 2021-11-06 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bhavcopyrec',
            name='sc_net_turnover',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='bhavcopyrec',
            name='sc_no_of_shares',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='bhavcopyrec',
            name='sc_no_of_trades',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='bhavcopyrec',
            name='sc_prevclose',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='bhavcopyrec',
            name='sc_close',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='bhavcopyrec',
            name='sc_code',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='bhavcopyrec',
            name='sc_high',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='bhavcopyrec',
            name='sc_low',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='bhavcopyrec',
            name='sc_name',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='bhavcopyrec',
            name='sc_open',
            field=models.FloatField(null=True),
        ),
    ]
