# Generated by Django 3.1.7 on 2021-11-06 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0002_auto_20211106_0930'),
    ]

    operations = [
        migrations.AddField(
            model_name='bhavcopyrec',
            name='report_date',
            field=models.DateField(null=True),
        ),
    ]
