# Generated by Django 3.1.7 on 2021-11-06 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0003_bhavcopyrec_report_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bhavcopyrec',
            name='report_date',
            field=models.IntegerField(null=True),
        ),
    ]
